---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: "default/macvlan-vlan1141-nad-layer2, default/lb-bridge-1154-nad-layer2, default/lb-bridge-1155-nad-layer2, default/lb-bridge-1156-nad-layer2"
  labels:
    run: frr-v1
  name: frr-v1
  namespace: test-ns
spec:
  nodeSelector: 
    node-role.kubernetes.io/master: ''
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    sysctls:
    - name: net.ipv6.conf.all.disable_ipv6
      value: "1"
  containers:
  - name: frr
    image: quay.io/nsatsia/frr-ubi8-v1:v9.1-30f4de3dd0
    imagePullPolicy: IfNotPresent
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: frr-deploy-cfg
      mountPath: /etc/frr
    securityContext:
      capabilities:
        add:
        - CAP_NET_ADMIN
        - CAP_NET_RAW
        - CAP_NET_BIND_SERVICE
        - CAP_SYS_ADMIN
  volumes:
  - name: frr-deploy-cfg
    configMap:
      name: lab-frr-deploy-cfg-a
      defaultMode: 436
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lab-frr-deploy-cfg-a
  namespace: test-ns
data:
  frr.conf: |
    no ipv6 forwarding
    !
    vrf frr1150
     ip router-id 198.19.254.1
    exit-vrf
    !
    interface net1
     description vrf frr net1
     ip address 198.19.141.253/24
    exit
    !
    interface net2
     description vrf frr net2
     ip address 198.19.154.254/24
    exit
    !
    interface net3
     description vrf frr net3
     ip address 198.19.155.254/24
    exit
    !
    interface net4
     ip address 198.19.156.254/24
    exit
    !
    router ospf vrf frr1150
     network 198.19.0.0/16 area 0
    exit
    !
    end
  daemons: |     
    # This file tells the frr package which daemons to start.
    #
    # Sample configurations for these daemons can be found in
    # /usr/share/doc/frr/examples/.
    #
    # ATTENTION:
    #
    # When activating a daemons for the first time, a config file, even if it is
    # empty, has to be present *and* be owned by the user and group "frr", else
    # the daemons will not be started by /etc/init.d/frr. The permissions should
    # be u=rw,g=r,o=.
    # When using "vtysh" such a config file is also needed. It should be owned by
    # group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
    #
    # The watchfrr, zebra and staticd daemons are always started.
    #
    bgpd=yes
    ospfd=yes
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=yes
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=yes
    fabricd=no
    vrrpd=yes

    #
    # If this option is set the /etc/init.d/frr script automatically loads
    # the config via "vtysh -b" when the servers are started.
    # Check /etc/pam.d/frr if you intend to use "vtysh"!
    #
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1"
    ospfd_options="  -A 127.0.0.1"
    ospf6d_options=" -A ::1"
    ripd_options="   -A 127.0.0.1"
    ripngd_options=" -A ::1"
    isisd_options="  -A 127.0.0.1"
    pimd_options="   -A 127.0.0.1"
    ldpd_options="   -A 127.0.0.1"
    nhrpd_options="  -A 127.0.0.1"
    eigrpd_options=" -A 127.0.0.1"
    babeld_options=" -A 127.0.0.1"
    sharpd_options=" -A 127.0.0.1"
    pbrd_options="   -A 127.0.0.1"
    staticd_options="-A 127.0.0.1"
    bfdd_options="   -A 127.0.0.1"
    fabricd_options="-A 127.0.0.1"
    vrrpd_options="  -A 127.0.0.1"

    # configuration profile
    #
    #frr_profile="traditional"
    #frr_profile="datacenter"

    #
    # This is the maximum number of FD's that will be available.
    # Upon startup this is read by the control files and ulimit
    # is called.  Uncomment and use a reasonable value for your
    # setup if you are expecting a large number of peers in
    # say BGP.
    #MAX_FDS=1024

    # The list of daemons to watch is automatically generated by the init script.
    #watchfrr_options=""
    watchfrr_options="--netns=frr1150"

    # To make watchfrr create/join the specified netns, use the following option:
    #watchfrr_options="--netns"
    # This only has an effect in /etc/frr/<somename>/daemons, and you need to
    # start FRR with "/usr/lib/frr/frrinit.sh start <somename>".

    # for debugging purposes, you can specify a "wrap" command to start instead
    # of starting the daemons directly, e.g. to use valgrind on ospfd:
    #   ospfd_wrap="/usr/bin/valgrind"
    # or you can use "all_wrap" for all daemons, e.g. to use perf record:
    #   all_wrap="/usr/bin/perf record --call-graph -"
    # the normal daemons command is added to this at the end.

